### ISSUE TITLE
Issues with "Configurate"

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeAPI#454]
Config Files of Sponge plugins should be easy to read and to modify. Server admins spend hours configuring their servers.

The "Configurate library used by Sponge supports multiple formats (HOCON, YAML, JSON).
As far as I know, HOCON is the preferred format.

**Issues of "Configurate":**

* Config Nodes are ordered alphabetically. There is no way to control the order of nodes: 
  * https://github.com/zml2008/configurate/issues/18
* No support for multi-line comments
  * https://github.com/zml2008/configurate/issues/16
* Bad HOCON output and no way to control the formatting:
   * https://github.com/zml2008/configurate/issues/17
   * https://github.com/zml2008/configurate/issues/19

Unfortunately many of my submitted issues were closed immediately...

I think that the order and formatting of nodes is important for the readability and understandability. Example:

Example from a random Bukkit plugin config:
```yaml
# MySQL is optional and not required. It is slower and uses more space.
# If you prefer to use MySQL, enable the following and fill out the fields.
use-mysql: false
table-prefix: co_
mysql-host: localhost
mysql-port: 3306
mysql-database: database
mysql-username: root
mysql-password: password123
```
Becomes this when using "Configurate":
```properties
mysql-database=database
mysql-host=localhost
mysql-password=password123
mysql-port=3306
mysql-username=root
table-prefix="co_"
# MySQL is optional and not required. It is slower and uses more space. If you prefer to use MySQL, enable the following and fill out the fields.
use-mysql=false
```
